
//# 389. Find the Difference

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

// SOLUTION


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

var findTheDifference = function (s, t) {
    let obj = {};

    for (let i = 0; i < t.length; i++) {
        obj[t[i]] = obj[t[i]] ? obj[t[i]] += 1 : 1;
    }

    for (let i = 0; i < s.length; i++) {
        if (obj[s[i]] > 0) {
            obj[s[i]] -= 1;
        }
    }

    for (let key in obj) {
        if (obj[key] === 1) {
            return key
        }
    }
};
